#Creating stage with depends
#After deploy Build stages, we would like to have paralleling running on DevStage and QAStage
#ProdStage would like to run after complete of DevStage and QAStage

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: echo Build First Job
    - job: SecondJob
      steps:
      - bash: echo Build Second Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
    - job: DevFist
      steps:
      - bash: echo Dev First Job
    - job: DevSeccond
      steps:
      - bash: echo Dev Second Job
- stage: QADeploy
  dependsOn: Build
  jobs:
    - job: QAJob
      steps:
      - bash: echo QA First Job
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
    - job: ProductionsJob
      steps:
      - bash: echo Production First Job
